In [24]:
import numpy as np
import sympy
import qsymm
import math
#空间反演
Inverse=np.array([[-1,0,0,0,0,0],[0,-1,0,0,0,0],[0,0,1,0,0,0],[0,0,0,1,0,0],[0,0,0,0,1,0],
                  [0,0,0,0,0,1]])
IS = qsymm.inversion(3, Inverse)
print(Inverse)

R4z=1/(math.sqrt(2))*np.array([[1-1j,0,0,0,0,0],[0,1+1j,0,0,0,0],[0,0,1-1j,0,0,0],
              [0,0,0,1+1j,0,0],[0,0,0,0,-1-1j,0],[0,0,0,0,0,-1+1j]])
rot4z = qsymm.rotation(1/4,axis=[0,0,1],U=R4z)



R2x=np.array([[0,1j,0,0,0,0],[1j,0,0,0,0,0],[0,0,0,1j,0,0],[0,0,1j,0,0,0],[0,0,0,0,0,1j],
                  [0,0,0,0,1j,0]])

rot2x= qsymm.rotation(1/2, axis=[1,0,0],U=R2x)


T=np.array([[0,-1,0,0,0,0],[1,0,0,0,0,0],[0,0,0,1,0,0],[0,0,-1,0,0,0],[0,0,0,0,0,-1],
                  [0,0,0,0,1,0]])
TS = qsymm.time_reversal(3, T)

symmetries = [rot4z,rot2x,TS,IS]

dim = 3
total_power = 2

x= qsymm.continuum_hamiltonian(symmetries, dim, total_power, prettify=True)
qsymm.display_family(x)


[[-1  0  0  0  0  0]
 [ 0 -1  0  0  0  0]
 [ 0  0  1  0  0  0]
 [ 0  0  0  1  0  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  1]]


Matrix([
[1, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0]])

Matrix([
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0],
[0, 0, 1, 0, 0, 0],
[0, 0, 0, 1, 0, 0],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0]])

Matrix([
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 1]])

Matrix([
[           0,            0,           0, I*k_x + k_y, 0, 0],
[           0,            0, I*k_x - k_y,           0, 0, 0],
[           0, -I*k_x - k_y,           0,           0, 0, 0],
[-I*k_x + k_y,            0,           0,           0, 0, 0],
[           0,            0,           0,           0, 0, 0],
[           0,            0,           0,           0, 0, 0]])

Matrix([
[          0,           0, 0, 0, -I*k_x + k_y,            0],
[          0,           0, 0, 0,            0, -I*k_x - k_y],
[          0,           0, 0, 0,            0,            0],
[          0,           0, 0, 0,            0,            0],
[I*k_x + k_y,           0, 0, 0,            0,            0],
[          0, I*k_x - k_y, 0, 0,            0,            0]])

Matrix([
[     0,     0, I*k_z,      0, 0, 0],
[     0,     0,     0, -I*k_z, 0, 0],
[-I*k_z,     0,     0,      0, 0, 0],
[     0, I*k_z,     0,      0, 0, 0],
[     0,     0,     0,      0, 0, 0],
[     0,     0,     0,      0, 0, 0]])

Matrix([
[k_z**2,      0, 0, 0, 0, 0],
[     0, k_z**2, 0, 0, 0, 0],
[     0,      0, 0, 0, 0, 0],
[     0,      0, 0, 0, 0, 0],
[     0,      0, 0, 0, 0, 0],
[     0,      0, 0, 0, 0, 0]])

Matrix([
[0, 0,      0,      0, 0, 0],
[0, 0,      0,      0, 0, 0],
[0, 0, k_z**2,      0, 0, 0],
[0, 0,      0, k_z**2, 0, 0],
[0, 0,      0,      0, 0, 0],
[0, 0,      0,      0, 0, 0]])

Matrix([
[0, 0, 0, 0,      0,      0],
[0, 0, 0, 0,      0,      0],
[0, 0, 0, 0,      0,      0],
[0, 0, 0, 0,      0,      0],
[0, 0, 0, 0, k_z**2,      0],
[0, 0, 0, 0,      0, k_z**2]])

Matrix([
[0, 0,          0,         0,          0,         0],
[0, 0,          0,         0,          0,         0],
[0, 0,          0,         0,          0, I*k_x*k_y],
[0, 0,          0,         0, -I*k_x*k_y,         0],
[0, 0,          0, I*k_x*k_y,          0,         0],
[0, 0, -I*k_x*k_y,         0,          0,         0]])

Matrix([
[k_x**2 + k_y**2,               0, 0, 0, 0, 0],
[              0, k_x**2 + k_y**2, 0, 0, 0, 0],
[              0,               0, 0, 0, 0, 0],
[              0,               0, 0, 0, 0, 0],
[              0,               0, 0, 0, 0, 0],
[              0,               0, 0, 0, 0, 0]])

Matrix([
[0, 0,               0,               0, 0, 0],
[0, 0,               0,               0, 0, 0],
[0, 0, k_x**2 + k_y**2,               0, 0, 0],
[0, 0,               0, k_x**2 + k_y**2, 0, 0],
[0, 0,               0,               0, 0, 0],
[0, 0,               0,               0, 0, 0]])

Matrix([
[0, 0,                0,                0,                0,                0],
[0, 0,                0,                0,                0,                0],
[0, 0,                0,                0,                0, -k_x**2 + k_y**2],
[0, 0,                0,                0, -k_x**2 + k_y**2,                0],
[0, 0,                0, -k_x**2 + k_y**2,                0,                0],
[0, 0, -k_x**2 + k_y**2,                0,                0,                0]])

Matrix([
[0, 0, 0, 0,               0,               0],
[0, 0, 0, 0,               0,               0],
[0, 0, 0, 0,               0,               0],
[0, 0, 0, 0,               0,               0],
[0, 0, 0, 0, k_x**2 + k_y**2,               0],
[0, 0, 0, 0,               0, k_x**2 + k_y**2]])

Matrix([
[0, 0,                   0,                    0,                   0,                    0],
[0, 0,                   0,                    0,                   0,                    0],
[0, 0,                   0,                    0, k_x*k_z + I*k_y*k_z,                    0],
[0, 0,                   0,                    0,                   0, -k_x*k_z + I*k_y*k_z],
[0, 0, k_x*k_z - I*k_y*k_z,                    0,                   0,                    0],
[0, 0,                   0, -k_x*k_z - I*k_y*k_z,                   0,                    0]])

5


In [25]:
J = qsymm.groups.spin_matrices(3/2)
print(J)

[[[ 0.       +0.j         0.8660254+0.j         0.       +0.j
    0.       +0.j       ]
  [ 0.8660254+0.j         0.       +0.j         1.       +0.j
    0.       +0.j       ]
  [ 0.       +0.j         1.       +0.j         0.       +0.j
    0.8660254+0.j       ]
  [ 0.       +0.j         0.       +0.j         0.8660254+0.j
    0.       +0.j       ]]

 [[ 0.       +0.j         0.       -0.8660254j  0.       +0.j
    0.       +0.j       ]
  [ 0.       +0.8660254j  0.       +0.j         0.       -1.j
    0.       +0.j       ]
  [ 0.       +0.j         0.       +1.j         0.       +0.j
    0.       -0.8660254j]
  [ 0.       +0.j         0.       +0.j         0.       +0.8660254j
    0.       +0.j       ]]

 [[ 1.5      +0.j         0.       +0.j         0.       +0.j
    0.       +0.j       ]
  [ 0.       +0.j         0.5      +0.j         0.       +0.j
    0.       +0.j       ]
  [ 0.       +0.j         0.       +0.j        -0.5      +0.j
    0.       +0.j       ]
  [ 0.       +0.j    